const StorageActionTypes = {
  STORAGE_LOADED: "STORAGE_LOADED",
  STORAGE_CLEARED: "CLEAR_STORAGE",
  STORAGE_UPDATED: "STORAGE_UPDATED",
  STORAGE_REMOVED: "STORAGE_REMOVED"
};

export default StorageActionTypes;
